pool:
  vmImage: 'VS2017-Win2016'
  
variables:
  buildConfiguration: Release
  
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: test
    projects: '**/*.Tests.csproj'
    arguments: /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --configuration $(buildConfiguration) --logger trx
    
- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: pack
    arguments: --version-suffix beta.$(Build.BuildId) --configuration $(buildConfiguration) --output $(Build.ArtifactsStagingDirectory)
  
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**\*.trx'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)\dotnet\test\**\coverage.cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)\dotnet\CoverageReports'

- task: PublishBuildArtifacts@1
  
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: '$(Build.ArtifactStagingDirectory)\**\*.nupkg'
    publishFeedCredentials: 'NuGet Feed'
